### ISSUE TITLE
Authorization in URL fails with Domain-based Username

### ISSUE THREAD

**Issue by mike-carey** [cloudfoundry-incubator/stembuild#10]
The authorization for vCenter is passed by providing the username and password in the URL itself.  [`fmt.Sprintf("%s:%s@%s", username, password, url)`](https://github.com/cloudfoundry-incubator/stembuild/blob/e3bca8923e53650149b0f9e32687803925cb8d4b/iaas_cli/iaas_clients/vcenter_client.go#L22).

Some consumers use domain's in their usernames: `my-domain\username`.  The error provided from Golang is along the lines of invalid character in URL.

# Workaround
To workaround this issue, we modified the [`buildGovcCommand` function](https://github.com/cloudfoundry-incubator/stembuild/blob/e3bca8923e53650149b0f9e32687803925cb8d4b/iaas_cli/iaas_clients/vcenter_client.go#L187) to use the `Url` instead of `CredentialUrl` and exported `GOVC_USERNAME` and `GOVC_PASSWORD` prior to running the stembuild.

**Comment by kartiklunkad26** [comment]
@mike-carey We've built support for Domains in the vCenter username into stembuild itself. So the 2019.9 and 1803.14 should fix this issue. Please re-open it if it doesn't!
