### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by techgnosis** [cloudfoundry-incubator/stembuild#12]
Howdy

Would be lovely if this worked on macOS.

**Comment by kartiklunkad26** [comment]
Thanks for opening this issue. It absolutely does work on MacOS, but we do not publish artifacts for it. 

Unfortunately, we will not be publishing artifacts for MacOS anytime soon :(  But! The Readme contains a [section](https://github.com/cloudfoundry-incubator/stembuild#stembuild-for-macos) that has a set of steps to build stembuild for MacOS. 

Hope that helps you!
