### ISSUE TITLE
2019 Stemcell Build Failing - DISM Related Failure

### ISSUE THREAD

**Issue by timlharrison** [cloudfoundry-incubator/stembuild#13]
We are suddenly getting a DISM related failure every time we execute our 2019 Stemcell build pipeline in Concourse:

Could not prepare VM: unknown error Post http://<IP_address>:5985/wsman: read tcp <IP_address>:58604-><IP_address>:5985: read: connection reset by peer

In the VM, we can see that the c:\provision\log.log file shows this:

Error: Running Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase
Dism.exe failed
Failed to clean up the VM's disk. See 'c:\provision\log.log' for more info
Failed to prepare the VM. See 'c:\provisions\log.log' for more info.

Lastly, in the actual DISM log c:\windows\logs\dism.log we see:

Failed finalizing changes. - CDISMPackageManager::Internal_Finalize(hr:0x800f0806)
The operation could not be completed due to pending operations. - GetCbsErrorMsg
Failed processing package changes - CDISMPackageManager::StartComponentCleanupEx(hr:0x800f0806)
The operation could not be completed due to pending operations. - GetCbsErrorMsg
Failed to start component cleanup. - CPackageManagerCLIHandler::ProcessCmdLine_CleanupImage(hr:0x800f0806)
Failed while processing command clenaup-image. - CPackageManagerCLIHandler::ExecuteCmdLine(hr:0x800f0806)

This process worked fine for the previous several months of stemcells.

**Comment by pivotalgeorge** [comment]
Thank you for the report of this DISM issue. The underlying cause was the order in which stembuild ran some of its `construct` steps.

The issue should be resolved with the 2019.12 version of stembuild. Please use that or newer for building 2019 stemcells going forward.
