### ISSUE TITLE
SHA mismatch between deps.json and the new LGPO.exe (v3.0) breaks stembuild construct command 

### ISSUE THREAD

**Issue by artful-gopher** [cloudfoundry-incubator/stembuild#14]
**Description**
stembuild construct command fails with the following error:
```
Executing setup script 1 of 2...
2020-09-04T15:34:38.3947569-07:00 Found correct OS version: Windows Server 2019
2020-09-04T15:34:39.0666250-07:00 C:\provision/LGPO.zip does not have the correct hash
2020-09-04T15:34:39.0978807-07:00 One or more files are corrupted or missing.
2020-09-04T15:34:39.0978807-07:00 Failed to validate the required dependencies. See 'c:\provision\log.log' for more info.
2020-09-04T15:34:39.1135102-07:00 Failed to install Bosh dependencies. See 'c:\provision\log.log' for more info.
Could not prepare VM: powershell encountered an issue:
```
Upon further investigation into the failure, the following lines of code perform the SHA matching when AutomationHelpers.ps1 PowerShell script is executed 
https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-automation/blob/master/AutomationHelpers.ps1#L248-L256
For the LGPO.zip file, looks like the matching occurs between the following:

- SHA hash from deps.json file (file packaged in StemcellAutomation.zip)
- SHA hash created for LGPO.zip (present in the same directory as stembuild CLI) using the following PowerShell command:
`Get-FileHash -Path "$PSScriptRoot/$fileName"`

When these 2 hashes do not match, the errors that we see above occurs and the stembuild construct command terminates prematurely.

In order to confirm this issue, I also tried matching the 2 SHA hash values known to the target VM in two cases:

- _Case 1 - With LGPO.zip v3.0_
<img width="876" alt="Screen Shot 2020-09-05 at 5 27 48 PM" src="https://user-images.githubusercontent.com/22406707/92315627-310c1200-ef9d-11ea-801e-7a5ff43b9897.png">

- _Case 2 - With LGPO.zip v2.2_
![Screen Shot 2020-09-05 at 4 32 22 PM](https://user-images.githubusercontent.com/22406707/92315680-1ab28600-ef9e-11ea-8a97-c92ba7624d52.png)

As we can see in **Case 1**, the deps.json file still has an old hash (for LGPO `v2.2`) while the hash values created for the downloaded LGPO `v3.0` is different and that is how the mismatch occurs.

**Case 2** is to show that hash values matching work fine when using LGPO `v2.2` - but this version is no longer available to download from Microsoft's security toolkit. Looks like a change is required when creating the deps.json file in order to get the SHA hash value for LGPO `v3.0` in deps.json and resolve this issue. 
https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-automation/blob/master/mk-deps.rb#L9

**Steps to reproduce this behavior**

- Download LGPO.zip (extracting this zip will help you find the version of LGPO.exe from the PDF file) and make sure the LGPO version is `3.0` - Microsoft currently maintains only this version.
- Run stembuild construct command using stembuild CLI version 2019.25 from the same directory that has the LGPO.zip downloaded from the previous step.

**Release Version & Related Info**
- Stembuild CLI version - **v2019.25 (Linux)**
- LGPO.zip version - **v3.0**
- Windows OS for stemcell - **Windows 2019 Server**

**Comment by XenoPhex** [comment]
Will be fixed as part of [#174712910](https://www.pivotaltracker.com/story/show/174712910): Update pipeline to work with the latest LGPO.zip
