### ISSUE TITLE
Timeout running stembuild construct 

### ISSUE THREAD

**Issue by farukhkhan123** [cloudfoundry-incubator/stembuild#15]
We have noticed an issue with the stembuild release "stembuild-linux-x86_64-2019.26". When running stembuild construct <$args>, even though i am using static IP as a param, the call fails with the following error. 

Creating provision dir on target VM...succeeded.

Transferring ~20 MB to the Windows VM. Depending on your connection, the transfer may take 15-45 minutes
[09-10-20 10:02:42] Uploading... Error: Put "https://169.254.113.93:443/guestFile?id=605&token=5269accc-9c53-c2ad-f186-004056ac08e9605": dial tcp 169.254.113.93:443: connect: connection timed out
./stembuild-linux-x86_64-2019.26: Put "https://169.254.113.93:443/guestFile?id=605&token=5269accc-9c53-c2ad-f186-004056ac08e9605": dial tcp 169.254.113.93:443: connect: connection timed out
Could not prepare VM: vcenter_client - ./LGPO.zip could not be uploaded

 My static IP is 10.X.X.X and i have no idea where the 169.X.X.X is coming from. 
Upon testing the same contruct call with stembuild release "stembuild-linux-x86_64-2019.20" i was able to run the construct call successfully, however it got stuck at the end preparing the VM for reboot. 

Finished executing setup script.

WinRM has been disconnected so the VM can reboot. Preparing the VM to be shutdown.
2020-10-09T10:05:37.34296-04:00 Still preparing VM...
2020-10-09T10:06:38.079996-04:00 Still preparing VM...
2020-10-09T10:07:38.905482-04:00 Still preparing VM...
..
..
2020-10-09T10:53:18.100368-04:00 Still preparing VM...

**Comment by gaigaslab-operations** [comment]
This may be an issue with recent Windows updates as the same problem - with the same IP occurs using older versions of stembuild - 22, 25.

Version 2019.20 DOES work, though.

**Comment by gaigaslab-operations** [comment]
So, after running with `-debug`, I think it is relating to stembuild trying to talk to vCenter.

This is the debug output:

`Transferring ~20 MB to the Windows VM. Depending on your connection, the transfer may take 15-45 minutes
[15-10-20 21:31:43] Uploading... Error: Put "https://169.254.113.93:443/guestFile?id=616&token=<redacted>": dial tcp 169.254.113.93:443: connect: connection timed out
../stembuild-linux-x86_64-2019.27: Put "https://169.254.113.93:443/guestFile?id=616&token=<redacted>": dial tcp 169.254.113.93:443: connect: connection timed out
Could not prepare VM: vcenter_client - ./LGPO.zip could not be uploaded`

Where would this address be coming from?

**Comment by gaigaslab-operations** [comment]
We found the issue - it was an incorrect configuration on a label of the VMKernel NIC on the ESXi host on which the base image was running.  Migrating it to a properly configured host picked up the correct IP from the Management Network interface and the construct phase completed.
