### ISSUE TITLE
Sha mismatch in bosh-google-kvm-windows2019-go_agent v2019.28

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry-incubator/stembuild#16]
The latest release, v2019.28, has the following sha1 on bosh.io: `sha1:6fd044fef0b6b88e7ff76ea7b7594929e92f633a`. However when you actually download it and run `shasum` on it, it is actually: `08f796790fc1a
446a263141a49db462a1ded1320`. This causes our concourse resource to refuse to download the release.

cc @cloudfoundry-incubator/cf-garden

**Comment by XenoPhex** [comment]
We'll look into this now, thanks for the info!

**Comment by XenoPhex** [comment]
I fixed the SHAs in this commit: https://github.com/bosh-io/stemcells-windows-index/commit/b77be11148ab3aee8286c95f2b21fddd7fe098cd and bosh.io will [hopefully] get updated within the hour.

However, Concourse may have trouble refreshing the old data; this may require you to run a `fly check-resource` command or [unfortunately] some Concourse DB surgery. I'd check with the Concourse team to determine the best to deal with this resource/sha mismatch issue if the `fly check-resource` command doesn't update the SHA correctly.
