### ISSUE TITLE
invalid cross-device link

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-incubator/stembuild#2]
you cannot set a hardlink between devices in docker

to solve this we should be able to set the `tmpdir`
or really move the file instead of a hardlink

```
running stembuild command: [[ stembuild -vmdk "/tmp/build/ebb6a6cb/packer-vmx/packer-vmx-disk1.vmdk" -v "1200.3" -output "/tmp/build/ebb6a6cb/packer-vmx" ]]
Error: rename /tmp/stemcell-614988369/bosh-stemcell-1200.3-vsphere-esxi-windows2012R2-go_agent.tgz /tmp/build/ebb6a6cb/packer-vmx/bosh-stemcell-1200.3-vsphere-esxi-windows2012R2-go_agent.tgz: invalid cross-device link
```

**Comment by charlievieth** [comment]
I belive it's the rename that's failing, adding a 'tmpdir' flag makes sense.  Stembuild should also rally back to copying the file when the tmp directory and destination are in different devices as appears to be the case here from the error message.

**Comment by jfmyers9** [comment]
If this is for Linux, have you tried setting the `TMPDIR` environment variable while using stembuild? It appears that [the code](https://github.com/pivotal-cf-experimental/stembuild/blob/master/tempdir_portable.go#L8) uses `os.TempDir("", ...` which will default to `os.TempDir()`  which respects the `TMPDIR` environment variable. https://golang.org/pkg/os/#TempDir


If this is for Windows, it appears that the [code](https://github.com/pivotal-cf-experimental/stembuild/blob/master/tempdir_windows.go#L10-L17) uses `%WINDIR%\Temp`. This may not be flexible enough. I wonder if it would be ok for us to default to the default behavior of `os.TempDir` for Windows as well which respects the following: `first non-empty value from %TMP%, %TEMP%, %USERPROFILE%, or the Windows directory`. I see this [commit](https://github.com/pivotal-cf-experimental/stembuild/commit/4c313342c0f3a07344da028dcb925678a743612b) gives an explanation for why `os.TempDir` may not be acceptable for Windows.

**Comment by xtreme-sameer-vohra** [comment]
Hi @ramonskie 
Were you able to try jfmyers9's suggestion ? If so, did it work for you ?

**Comment by ramonskie** [comment]
@xtreme-sameer-vohra no i haven't had the time and i'm using a workaround for this at the moment

**Comment by rguilme1** [comment]
I set TMPDIR to a directory on the same device as my output directory and this workaround worked for me.

Regards
    - Rick
