### ISSUE TITLE
[enhancement] Power on VM

### ISSUE THREAD

**Issue by ddieruf** [cloudfoundry-incubator/stembuild#9]
When running `construct` check if the VM is powered on, instead of expecting it to be on. Turn it on if it's not. Currently, an error is shown `ServerFaultCode: The attempted operation cannot be performed in the current state (Powered off).`.

**Comment by kartiklunkad26** [comment]
Thanks for providing this feedback. We will provide updates if we do build this feature.

**Comment by sneal** [comment]
Unfortunately it's not as easy as throwing in a `govc vm.power -on -wait VMNAME` as it doesn't wait long enough for the OS to boot so you end with `Creating provision dir on target VM..../stembuild: ServerFaultCode: The guest operations agent could not be contacted.`
